### ISSUE TITLE
Adding a new program called " C++ program for pascal triangle" in the basic folder

### ISSUE THREAD

**Issue by MonishRaman** [Yaser-123/Cpp-Fundamentals#1]
Pascal’s triangle is a triangular array of the binomial coefficients. Write a function that takes an integer value n as input and prints first n lines of the Pascal’s triangle. Following are the first 6 rows of Pascal’s Triangle.

1  
1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 
1 5 10 10 5 1

Time Complexity : O(n^2)  and space complexity : O(n^2)

**Comment by Yaser-123** [comment]
@MonishRaman 
work on it !!
