### ISSUE TITLE
Insertion and deletions in singly and doubly linked list

### ISSUE THREAD

**Issue by Arisha2902** [Yaser-123/Cpp-Fundamentals#3]
@Yaser-123 , I can write code for insertion and deletion in singly and doubly linked list
I got to know about ur repo through github , if u need any help in python, do contact me

**Comment by Yaser-123** [comment]
@Arisha2902 
Thanks for reaching out! Feel free to go ahead and contribute the code for insertion and deletion in linked lists. I’ll definitely contact you if I need help with Python. 😊 By the way, if you're working on any project, I'd be happy to contribute!
